name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests and collect coverage
        run: npx nx run-many --target=test --all

      - name: Upload coverage to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=frankpeterandrae_angular-apps
            -Dsonar.organization=frankpeterandrae
            -Dsonar.sources=apps,libs
            -Dsonar.test.inclusions=**/*.spec.ts,**/*.test-setup.ts
            -Dsonar.coverage.exclusions=**/*.js,**/main.ts,**/*environment*.ts,**/*.scss,**/*.css,**/*.json,**/demo-e2e/**,**/homepage-e2e/**,**/*test-setup.ts,**/*app.config.ts,**/*app.routes.ts,**/*.php
            -Dsonar.javascript.lcov.reportPaths=coverage/apps/demo/lcov.info,coverage/apps/homepage/lcov.info,coverage/libs/colour-rack/lcov.info,coverage/libs/demo/domain/lcov.info,coverage/libs/homepage/domain/lcov.info,coverage/libs/homepage/feature/lcov.info,coverage/libs/shared/config/lcov.info,coverage/libs/shared/services/lcov.info,coverage/libs/shared/ui-theme/lcov.info
