name: Deploy to FTP Server

on:
  push:
    branches:
      - main  # Adjust this to your deployment branch

jobs:
  sonarcloud:
    uses: ./.github/workflows/sonarcloud-main.yml  # Path to the reusable workflow

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build Angular app
        run: npx nx run homepage:build-production

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/production/
          server-dir: /html/
          protocol: ftps
